### ISSUE TITLE
Note Management

### ISSUE THREAD

**Issue by wasimanitoba** [wasimanitoba/InvolvedTowns#1]
### Goal

We want a platform for user to record hypotheses and evidence related to political-science, economics and public policy which can be shared for analysis or refutation.

#### Forum-Specific Changes

- [x] Users' forum comments can be saved directly to the database
- [x] User forum entries can be tagged, saved by the user
- [x] Any non-admin user can submit forum posts

#### Note functionality

- [x] Users can delete notes

### Roadmap

This will provide a foundation for later features:

- Ontologies: organized, shareable trees of assertions with supporting evidence
- Inference: automated logical deduction using ontologies
- Delegate voting: networks of trust formalized with transferable proxy voting
