### ISSUE TITLE
Note management

### ISSUE THREAD

**Issue by wasimanitoba** [wasimanitoba/InvolvedTowns#1]
### Goal

We want a platform for user to record hypotheses and evidence related to political-science, economics and public policy which can be shared for analysis or refutation.

### Details

- [ ] Users can import bookmarks, web annotations and stored notes from the sister project
- [ ] Users can make their entries public or private
- [ ] Users can 'fork' and merge other users' public entries into their own repository
- [ ] Users can 'vote' on categorizing entries by assigning descriptive tags

### Roadmap

This will provide a foundation for later features:

- Ontologies: organized, shareable trees of assertions with supporting evidence
- Inference: automated logical deduction using ontologies
- Delegate voting: networks of trust formalized with transferable proxy voting
